export const ADD_SPENDING_REQUEST = "ADD_SPENDING_REQUEST";
export const ADD_SPENDING_SUCCESS = "ADD_SPENDING_SUCCESS";
export const ADD_SPENDING_FAILURE = "ADD_SPENDING_FAILURE";
export const FETCH_SPENDING_REQUEST = "FETCH_SPENDING_REQUEST";
export const FETCH_SPENDING_SUCCESS = "FETCH_SPENDING_SUCCESS";
export const FETCH_SPENDING_FAILURE = "FETCH_SPENDING_FAILURE";
